config/routes.rb
Tendenciazero::Application.routes.draw do

  resources :users do
    member do
      get 'password'
      put 'update_password'
      get 'user_type'
      put 'update_user_type'
    end
  end

  root :to => 'home#index'

  resources :user_types
  resources :galleries, :path => "gallery"
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password        :string(255)
#  user_type_id    :integer
#  password_digest :string(255)
#  remember_token  :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :user_type_id, :user_type, :password_confirmation

  attr_accessor :skip_password_validation

  belongs_to :user_type, :foreign_key => "user_type_id"

  has_secure_password

  before_save { email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50, minimum: 3 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, :presence => true, length: { minimum: 6 }, :unless => :skip_password_validation
  validates :password_confirmation, presence: true, :unless => :skip_password_validation



  def custom_update_attributes(params)
    if params[:password].blank?
      params.delete :password
      params.delete :password_confirmation
      update_attributes params
    end
  end

  def admin?
    if (self.user_type == UserType.find_by_name('Admin')) && (self.user_type!= nil)
      return true
    else
      return false
    end
  end  

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/user_type.rb
# == Schema Information
#
# Table name: user_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserType < ActiveRecord::Base
  attr_accessible :name
  has_many :users
  validates :name, presence: true, length: { maximum: 50, minimum:3 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      @user.user_type = UserType.find_by_name("Visitante")
      if @user.save
        if signed_in?
          sign_in current_user
        else
          sign_in @user
        end
        format.html { redirect_to @user, notice: 'Usuario creado exitosamente.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      @user.skip_password_validation = true
      if @user.custom_update_attributes(params[:user])
        if current_user.admin?
          sign_in current_user
        else
          sign_in @user
        end
        format.html { redirect_to @user, notice: 'Perfil actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def password
    @user = User.find(params[:id])
  end

  def update_password
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        if current_user.admin?
          sign_in current_user
        else
          sign_in @user
        end
        format.html { redirect_to @user, notice: 'Password actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "password" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def user_type
    @user = User.find(params[:id])
  end

  def update_user_type
    @user = User.find(params[:id])

    respond_to do |format|
      @user.skip_password_validation = true
      if @user.custom_update_attributes(params[:user])
        if current_user.admin?
          sign_in current_user
        end
        format.html { redirect_to @user, notice: 'Usuario actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "user_type" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="reg_form" class="bg_form">
	<h2>Editar Perfil</h2>

	<div class="row">
    <div class="span6">
    	<%= form_for(@user) do |f| %>
	    	<%= render 'error_messages' %>

				<%= f.label :nombre, :class => "label_form" %>
			  <%= f.text_field :name, :class => "text_field_form", :required => true  %>

			  <%= f.label :email, :class => "label_form" %>
			  <%= f.text_field :email, :class => "text_field_form" , :required => true %>

			  <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
		  <% end %>
		  <hr>
			<p>
				<%= link_to 'Regresar', @user %> -
				<%= link_to 'Cambiar contraseña', password_user_path(@user) %>
				<% if can? :update_user_type, User %>
				- <%= link_to 'Cambiar tipo de usuario', user_type_user_path(@user) %>
				<% end %>
			</p>
		</div>
  </div>
</div>

app/views/users/index.html.erb
<div id="reg_form" class="bg_form">
  <h2>Listado de usuarios registrados</h2>

  <% @users.each do |user| %>
    <hr>
    <div class="user">
        <p><%= user.name %></p>
        <p><%= user.email %></p>
        <% if (!user.user_type.nil?) %>
          <p><%= user.user_type.name %></p>
        <% end %>
        <p><%= link_to 'Mostrar', user %>
          <% if can? :update, User %>
          - <%= link_to 'Editar', edit_user_path(user) %>
          <% end %>
          <% if can? :destroy, User %>
          - <%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Estas seguro?' } %></p>
          <% end %>
    </div>
  <% end %>
  <hr>
  <% if can? :create, User %>
    <%= link_to 'Nuevo usuario', new_user_path, class: "btn btn-primary btn_form" %>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Registro') %>
<div id="reg_form" class="bg_form">
  <h2>Registrate</h2>

  <div class="row">
    <div class="span6">
      <%= form_for(@user) do |f| %>
        <%= render 'error_messages' %>

        <%= f.label :name, "Nombre", :class => "label_form" %>
        <%= f.text_field :name, :class => "text_field_form", :required => true%>

        <%= f.label :email, :class => "label_form" %>
        <%= f.text_field :email, :class => "text_field_form", :required => true %>

        <%= f.label :password, :class => "label_form" %>
        <%= f.password_field :password, :class => "text_field_form", :required => true %>

        <%= f.label :password_confirmation, "Confirmar password", :class => "label_form" %>
        <%= f.password_field :password_confirmation, :class => "text_field_form", :required => true %>

        <%= f.submit "Crear mi cuenta", class: "btn btn-primary btn_form" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/password.html.erb
<div id="reg_form" class="bg_form">
	<h2>Cambiar contraseña</h2>

	<div class="row">
    <div class="span6">
    	<%= form_for @user, :url => { :action => "update_password" } do |f| %>
    		<%= render 'error_messages' %>

		    <%= f.label :password, "Nueva contraseña", :class => "label_form" %>
        <%= f.password_field :password, :class => "text_field_form" %>

        <%= f.label :password_confirmation, "Confirmar contraseña", :class => "label_form" %>
        <%= f.password_field :password_confirmation, :class => "text_field_form" %>

		    <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
		  <% end %>
		  <hr>
			<%= link_to 'Regresar', @user %>
		</div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div id="reg_form" class="bg_form">
    <h2>Perfil de usuario</h2>
      <p>
      <b>Nombre:</b>
      <%= @user.name %>
    </p>
    <p>
      <b>Email:</b>
      <%= @user.email %>
    </p>
    <% if (!@user.user_type.nil?) %>
      <p>
        <b>Tipo de usuario:</b>
        <%= @user.user_type.name %>
      </p>
    <% end %>
    <hr>
    <% if can? :update, User %>
    <%= link_to 'Editar Perfil', edit_user_path(@user) %> |
    <% end %>
    <%= link_to 'Regresar', users_path %>
  </div>
</div>

app/views/users/user_type.html.erb
<% provide(:title, @user.name) %>
<div id="reg_form" class="bg_form">
	<h2>Cambiar tipo de usuario</h2>

	<div class="row">
    <div class="span6">
    	<%= form_for @user, :url => { :action => "update_user_type" } do |f| %>
    		<%= render 'error_messages' %>
    		<hr>
    		<%= f.label :user, "Usuario: #{@user.name}  - #{@user.email}", :class => "label_form" %>
    		<br>
		    <%= f.label :user_type, "Tipo de Usuario", :class => "label_form" %>
		    <%= f.collection_select :user_type_id, UserType.all, :id, :name, {:selected => @user.user_type.id},:class => "select_form" %>

		    <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
		  <% end %>
		  <hr>
			<%= link_to 'Regresar', @user %>
		</div>
  </div>
</div>