config/routes.rb
Tendenciazero::Application.routes.draw do

  resources :users do
    member do
      get 'password'
      put 'update_password'
      get 'user_type'
      put 'update_user_type'
    end
  end

  root :to => 'home#index'

  resources :user_types
  resources :galleries, :path => "gallery"
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  # GET /user_types
  # GET /user_types.json
  def index
    @user_types = UserType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_types }
    end
  end

  # GET /user_types/1
  # GET /user_types/1.json
  def show
    @user_type = UserType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_type }
    end
  end

  # GET /user_types/new
  # GET /user_types/new.json
  def new
    @user_type = UserType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_type }
    end
  end

  # GET /user_types/1/edit
  def edit
    @user_type = UserType.find(params[:id])
  end

  # POST /user_types
  # POST /user_types.json
  def create
    @user_type = UserType.new(params[:user_type])

    respond_to do |format|
      if @user_type.save
        format.html { redirect_to @user_type, notice: 'Tipo de Usuario creado exitosamente.' }
        format.json { render json: @user_type, status: :created, location: @user_type }
      else
        format.html { render action: "new" }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_types/1
  # PUT /user_types/1.json
  def update
    @user_type = UserType.find(params[:id])

    respond_to do |format|
      if @user_type.update_attributes(params[:user_type])
        format.html { redirect_to @user_type, notice: 'Tipo de Usuario actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_types/1
  # DELETE /user_types/1.json
  def destroy
    @user_type = UserType.find(params[:id])
    @user_type.destroy

    respond_to do |format|
      format.html { redirect_to user_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/user_types/_error_messages.html.erb
<% if @user_type.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(@user_type.errors.count, "error") %>.
    </div>
    <ul>
    <% @user_type.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/user_types/_form.html.erb
<%= form_for(@user_type) do |f| %>
  <%= render 'error_messages' %>

  <%= f.label :nombre, :class => "label_form" %>
  <%= f.text_field :name, :class => "text_field_form", :required => true  %>

  <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
  <hr>
<% end %>

app/views/user_types/edit.html.erb
<div id="reg_form" class="bg_form">
	<h2>Editar tipo de usuario</h2>
	<%= render 'form' %>
	<%= link_to 'Mostrar', @user_type %> |
	<%= link_to 'Regresar', user_types_path %>
</div>

app/views/user_types/index.html.erb
<div id="reg_form" class="bg_form">
  <h2>Listado de Tipos de Usuario</h2>

  <% @user_types.each do |user_type| %>
    <hr>
    <div class="user_type">
      <p><%= user_type.name %></p>
      <p>
        <%= link_to 'Mostrar', user_type %> -
        <%= link_to 'Editar', edit_user_type_path(user_type) %> -
        <%= link_to 'Eliminar', user_type, method: :delete, data: { confirm: '¿Estas seguro?' } %>
      </p>
    </div>
  <% end %>
  <hr>
  <%= link_to 'Nuevo tipo de usuario', new_user_type_path, class: "btn btn-primary btn_form" %>
</div>

app/views/user_types/new.html.erb
<div id="reg_form" class="bg_form">
	<h2>Nuevo tipo de usuario</h2>
	<%= render 'form' %>
	<%= link_to 'Regresar', user_types_path %>
</div>

app/views/user_types/show.html.erb
<% provide(:title, @user_type.name) %>
<div class="row">
  <div id="reg_form" class="bg_form">
    <h2>Tipo de usuario</h2>
		<p>
		  <b>Nombre:</b>
		  <%= @user_type.name %>
		</p>
    <hr>
    <%= link_to 'Editar', edit_user_type_path(@user_type) %> |
		<%= link_to 'Regresar', user_types_path %>
  </div>
</div>