config/routes.rb
Tendenciazero::Application.routes.draw do

  resources :users do
    member do
      get 'password'
      put 'update_password'
      get 'user_type'
      put 'update_user_type'
    end
  end

  root :to => 'home#index'

  resources :user_types
  resources :galleries, :path => "gallery"
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Gallery < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Galeria de Imagenes creada exitosamente.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Galeria de Imagenes actualizada exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_error_messages.html.erb
<% if @gallery.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(@gallery.errors.count, "error") %>.
    </div>
    <ul>
    <% @gallery.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <%= render 'error_messages' %>

  <%= f.label :nombre, :class => "label_form" %>
  <%= f.text_field :name, :class => "text_field_form", :required => true %>

  <%= f.label :descripcion, :class => "label_form" %>
  <%= f.text_area :description, :class => "text_field_form", :size => "50x10"  %>

  <%= f.submit "Guardar", class: "btn btn-primary btn_form"%>
  <hr>
<% end %>

app/views/galleries/edit.html.erb
<div id="reg_form" class="bg_form">
	<h2>Editar galeria de imagenes</h2>
	<%= render 'form' %>
	<%= link_to 'Mostrar', @gallery %> |
	<%= link_to 'Regresar', galleries_path %>
</div>

app/views/galleries/index.html.erb
<div id="reg_form" class="bg_form">
  <h2>Listado de Galerias de Imagenes</h2>

  <% @galleries.each do |gallery| %>
    <hr>
    <div class="gallery">
      <p><%= gallery.name %></p>
      <p><%= gallery.description %></p>
      <p>
        <%= link_to 'Mostrar', gallery %> -
        <%= link_to 'Editar', edit_gallery_path(gallery) %> -
        <%= link_to 'Eliminar', gallery, method: :delete, data: { confirm: '¿Estas seguro?' } %>
      </p>
    </div>
  <% end %>
  <hr>
  <%= link_to 'Nueva Galeria de Imagenes', new_gallery_path, class: "btn btn-primary btn_form" %>
</div>

app/views/galleries/new.html.erb
<div id="reg_form" class="bg_form">
	<h2>Nueva Galeria de Imagenes</h2>
	<%= render 'form' %>
	<%= link_to 'Regresar', galleries_path %>
</div>

app/views/galleries/show.html.erb
<% provide(:title, @gallery.name) %>
<div class="row">
  <div id="reg_form" class="bg_form">
    <h2>Galeria de Imagenes</h2>
		<p>
		  <b>Nombre:</b>
		  <%= @gallery.name %>
		</p>
		<p>
		  <b>Descripcion:</b>
		  <%= @gallery.description %>
		</p>
    <hr>
    <%= link_to 'Editar', edit_gallery_path(@gallery) %> |
		<%= link_to 'Regresar', galleries_path %>
  </div>
</div>