config/routes.rb
Tendenciazero::Application.routes.draw do

  resources :users do
    member do
      get 'password'
      put 'update_password'
      get 'user_type'
      put 'update_user_type'
    end
  end

  root :to => 'home#index'

  resources :user_types
  resources :galleries, :path => "gallery"
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<div class="container">
  <p class="text-center">Todos los derechos reservados - Andres Diaz - 2013</p>
</div>

app/views/layouts/_messages.html.erb
<div style="position:absolute; top:15%; z-index:1000; width: 200px; right: 5%;">
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	      <a class="close" data-dismiss="alert">&#215;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Tendencia Zero Ingenieria", root_path, :class => 'brand' %>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<div class="nav-collapse">
  <ul class="nav pull-right">
    <li><%= link_to "Inicio", root_path, :class => 'home_link' %></li>
    <li><%= link_to "Conocenos", root_path, :class => 'home_link' %></li>
    <li><%= link_to "Portafolio", root_path, :class => 'home_link' %></li>
    <li><%= link_to "Galeria", root_path, :class => 'home_link' %></li>
    <li><%= link_to "Contacto", root_path, :class => 'home_link' %></li>
    <li><%= link_to "Redes", root_path, :class => 'home_link' %></li>
    <li class="dropdown" id="accountmenu">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= image_tag("user.png", :alt => "Usuarios") %>
        <% if signed_in? %>
            <span><%= current_user.name %></span>
        <% end %>
      </a>
      <ul class="dropdown-menu">
        <% if signed_in? %>
          <li><%= link_to "Mi perfil: "+current_user.name, current_user %></li>
          <li class="divider"></li>
          <li><%= link_to "Salir", signout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Ingresar", signin_path %></li>
          <li><%= link_to "Registrate", signup_path %></li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="author" content="duende84">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!--[if IE 9 ]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <%= image_tag("/assets/logo2.png", :alt => "TendenciaZero", :class => "logo")%>
      <% if signed_in? %>
        <%= link_to "Cerrar Sesión", signout_path, method: "delete", :id => 'btn_logout', :class => 'button2 rounded gold' %>
      <% else %>
        <%= link_to "Iniciar Sesión", signin_path, :id => 'btn_login', :class => 'button2 rounded gold' %>
      <% end %>
    </header>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>